name:  Whatsapp Notify
on:
  issue_comment:
    types: created
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  issues:
    types: [opened, edited, pinned, closed, reopened, assigned, labeled]
  page_build:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: wa-notify
        uses: mdb571/wa-action@master
        with:
          from: ${{+14155238886}}
          to: ${{+6590736979}}
        env:
          TWILIO_ACCOUNT_SID: ${{SK21abe1dd905c397e8572545611c83a77}}
          TWILIO_AUTH_TOKEN: ${{Go2htcZBCuiOTVayo8HgvUzkNvJdk9Rp}}